eureka:
  client:
    serviceUrl:
        defaultZone: http://node1:8771/eureka/,http://node2:8772/eureka/
server:
  port: 8765
spring:
  application:
    name: serviceConsumerByFeign

feign:
   hystrix:
      enabled: true

serviceprovider: #服务名
  ribbon:
  #按响应时间的权重分配请求，时间越短，权重越大，分配到请求的几率越大
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
