#默认注册地址
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

#management:
#  contextPath: /eurekaclient1

#传给注册中心的实例信息
eureka:
  instance:
    hostname: localhost
#    preferIpAddress: true
    #心跳时间，客户端注册服务元数据注册中心
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    homePageUrlPath: ${server.servletPath}
    statusPageUrlPath: ${server.servletPath}/info
    healthCheckUrlPath: ${server.servletPath}/health
    #对应"metadata":{"instanceId":"eurekaclient:56929cfd113d3fe33d3d3df34715d780"
    metadataMap:
          instanceId: ${spring.application.name}:${random.value}
  client:
#      fetchRegistry: true #从注册中心获取最新服务，更新本地缓存
#      healthcheck:
#              enabled: true
      serviceUrl:
        defaultZone: http://node1:8771/eureka/,http://node2:8772/eureka/


server:
  port: 8762
#  servletPath: /
spring:
  application:
    name: serviceProvider
  profiles: serviceProvider-1

---
eureka:
  instance:
    hostname: localhost
#    preferIpAddress: true
    #心跳时间，客户端注册服务元数据注册中心
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    homePageUrlPath: ${server.servletPath}
    statusPageUrlPath: ${server.servletPath}/info
    healthCheckUrlPath: ${server.servletPath}/health
    #对应"metadata":{"instanceId":"eurekaclient:56929cfd113d3fe33d3d3df34715d780"
    metadataMap:
          instanceId: ${spring.application.name}:${random.value}
  client:
#      fetchRegistry: true #从注册中心获取最新服务，更新本地缓存
#      healthcheck:
#              enabled: true
      serviceUrl:
        defaultZone: http://node1:8771/eureka/,http://node2:8772/eureka/


server:
  port: 8763
#  servletPath: /
spring:
  application:
    name: serviceProvider
  profiles: serviceProvider-2


