eureka:
  client:
    serviceUrl:
        defaultZone: http://node1:8771/eureka/,http://node2:8772/eureka/
server:
  port: 8001
spring:
  application:
    name: hystrixTurbine


turbine:
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  # 要监控的应用名，也是注册到注册中心的服务名
  appConfig: serviceConsumerByFeign,serviceConsumerByRibbon
